// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aRANRLPd4otPtCuNvZtsnZ
// Component: 27GTtwlekzAr

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useScreenVariants as useScreenVariantsbPzZ2WR5Unx5 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: bPzZ2wR5unx5/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: aRANRLPd4otPtCuNvZtsnZ/projectcss
import sty from "./PlasmicLogoKoi.module.css"; // plasmic-import: 27GTtwlekzAr/css

createPlasmicElementProxy;

export type PlasmicLogoKoi__VariantMembers = {};
export type PlasmicLogoKoi__VariantsArgs = {};
type VariantPropType = keyof PlasmicLogoKoi__VariantsArgs;
export const PlasmicLogoKoi__VariantProps = new Array<VariantPropType>();

export type PlasmicLogoKoi__ArgsType = {};
type ArgPropType = keyof PlasmicLogoKoi__ArgsType;
export const PlasmicLogoKoi__ArgProps = new Array<ArgPropType>();

export type PlasmicLogoKoi__OverridesType = {
  root?: Flex__<typeof PlasmicImg__>;
};

export interface DefaultLogoKoiProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLogoKoi__RenderFunc(props: {
  variants: PlasmicLogoKoi__VariantsArgs;
  args: PlasmicLogoKoi__ArgsType;
  overrides: PlasmicLogoKoi__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsbPzZ2WR5Unx5()
  });

  return (
    <PlasmicImg__
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      alt={""}
      className={classNames(
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
      displayHeight={
        hasVariant(globalVariants, "screen", "mobileOnly") ? "128px" : "auto"
      }
      displayMaxHeight={"none"}
      displayMaxWidth={"100%"}
      displayMinHeight={"0"}
      displayMinWidth={"0"}
      displayWidth={
        hasVariant(globalVariants, "screen", "mobileOnly") ? "127px" : "120px"
      }
      loading={"lazy"}
      src={{
        src: "/plasmic/koi/images/group2Png.png",
        fullWidth: 121,
        fullHeight: 120,
        aspectRatio: undefined
      }}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof PlasmicImg__;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLogoKoi__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLogoKoi__VariantsArgs;
    args?: PlasmicLogoKoi__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLogoKoi__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicLogoKoi__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLogoKoi__ArgProps,
          internalVariantPropNames: PlasmicLogoKoi__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLogoKoi__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLogoKoi";
  } else {
    func.displayName = `PlasmicLogoKoi.${nodeName}`;
  }
  return func;
}

export const PlasmicLogoKoi = Object.assign(
  // Top-level PlasmicLogoKoi renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicLogoKoi
    internalVariantProps: PlasmicLogoKoi__VariantProps,
    internalArgProps: PlasmicLogoKoi__ArgProps
  }
);

export default PlasmicLogoKoi;
/* prettier-ignore-end */
